### Import libraries

The Material Dataset includes the following mechanical properties:

- Standard (Std)
- Unique Identification code for the Material (ID)
- Material Name
- Heat Treatment Method
- Ultimate Tensile Strength (Su) in MPa
- Yield Strength (Sy) in MPa
- Elongation at Break or Strain (A5) as a Percentage
- Brinell Hardness Number (BHN) in Microhardness Units
- Elastic Modulus (E) in MPa
- Shear Modulus (G) in MPa
- Poisson's Ratio (mu) in Units of Length
- Density (Ro) in Kg/m3
- Pressure at Yield (pH) in MPa
- Description of the Material (Desc)
- Vickers Hardness Number (HV)

Here, there are 15 columns called features/attributes in Machine Learning. We are going to use only 7, which are (ID, Ultimate Tensile Strength, Yield Strength, Young’s Modulus, Shear Modulus, Poisson's Ratio, and Density) since other features have missing data.
We added an 8th column in the dataset called Use which contains binary values (Yes/No). This column is called Label. The Label contains Yes or No values.

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Read dataset

In [11]:
df = pd.read_csv("Data.csv")
df.head()

,Std,ID,Material,Heat treatment,Su,Sy,A5,Bhn,E,G,mu,Ro,pH,Desc,HV
0,ANSI,D8894772B88F495093C43AF905AB6373,Steel SAE 1015,as-rolled,421,314,39.0,126.0,207000,79000,0.3,7860,NaN,NaN,NaN
1,ANSI,05982AC66F064F9EBC709E7A4164613A,Steel SAE 1015,normalized,424,324,37.0,121.0,207000,79000,0.3,7860,NaN,NaN,NaN
2,ANSI,356D6E63FF9A49A3AB23BF66BAC85DC3,Steel SAE 1015,annealed,386,284,37.0,111.0,207000,79000,0.3,7860,NaN,NaN,NaN
3,ANSI,1C758F8714AC4E0D9BD8D8AE1625AECD,Steel SAE 1020,as-rolled,448,331,36.0,143.0,207000,79000,0.3,7860,NaN,NaN,NaN
4,ANSI,DCE10036FC1946FC8C9108D598D116AD,Steel SAE 1020,normalized,441,346,35.8,131.0,207000,79000,0.3,7860,550.0,NaN,NaN

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1552 entries, 0 to 1551
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Std             1552 non-null   object
 1   ID              1552 non-null   object
 2   Material        1552 non-null   object
 3   Heat treatment  802 non-null    object
 4   Su              1552 non-null   int64
 5   Sy              1552 non-null   object
 6   A5              1346 non-null   float64
 7   Bhn             463 non-null    float64
 8   E               1552 non-null   int64
 9   G               1552 non-null   int64
 10  mu              1552 non-null   float64
 11  Ro              1552 non-null   int64
 12  pH              193 non-null    float64
 13  Desc            981 non-null    object
 14  HV              165 non-null    float64
dtypes: float64(5), int64(4), object(6)
memory usage: 182.0+ KB

In [41]:
df["Sy"] = df["Sy"].str.extract(r'(\d+)')  # Extract only numbers
df["Sy"] = df["Sy"].astype("int")  # Convert to integer

In [42]:
df.groupby(["Heat treatment"])[["Su", "Sy", "A5", "E"]].agg("mean")

,Su,Sy,A5,E
Heat treatment,,,,
1/2-hard,1034.000000,758.000000,12.500000,193000.000000
1/4-hard,862.000000,517.000000,17.250000,193000.000000
3/4-hard,1207.000000,931.000000,8.500000,193000.000000
Annealing,600.000000,360.000000,NaN,213000.000000
Annealing or high tempering,438.888889,285.555556,17.777778,205666.666667
As extruded,339.090909,228.272727,13.727273,78818.181818
As hot rolled,372.000000,138.000000,45.000000,105000.000000
"Case hardening,quenching and cooling in the oil",1000.000000,762.500000,9.500000,209250.000000
Cast (F or T5),224.800000,140.600000,4.600000,73000.000000
Cast (F),137.857143,70.000000,2.666667,73000.000000
Cast (T4),266.666667,145.000000,8.000000,73000.000000
Cast (T5),227.666667,179.333333,1.750000,73000.000000
Cast (T51),184.000000,140.000000,3.000000,73000.000000
Cast (T52),248.000000,207.000000,1.500000,73000.000000
Cast (T53),248.000000,186.000000,1.500000,73000.000000
Cast (T6),233.625000,159.375000,2.687500,73000.000000
Cast (T61),221.000000,138.000000,NaN,73000.000000
Cast (T62),248.000000,193.000000,NaN,73000.000000
Cast (T7),270.750000,215.500000,2.333333,73000.000000
Cast (T71),236.666667,195.333333,2.500000,73000.000000
Cast (T77),165.000000,90.000000,1.000000,73000.000000
Cold working,548.888889,355.555556,6.777778,205666.666667
Full-hard,1276.000000,965.000000,6.000000,193000.000000
Heat-treatment nitrided steel,807.000000,636.000000,NaN,206000.000000
Improved,829.166667,598.333333,15.250000,209250.000000
Quenched and tempered,797.492958,541.070423,14.098592,204408.450704
Quenching and cooling in the oil,1112.320000,936.240000,10.000000,211120.000000
Quenching and cooling in the water,878.615385,638.769231,NaN,205846.153846
Quenching and heating,810.000000,583.333333,NaN,201000.000000
Wrought,283.625616,216.847291,13.897959,73000.000000
annealed,613.545455,339.712121,33.443939,201484.848485
as-rolled,644.785714,399.857143,25.785714,207000.000000
case-hardened,785.181818,561.863636,10.000000,205681.818182
face hardened,867.000000,659.600000,12.625000,206000.000000
heat treated,1091.314815,881.759259,10.367347,206000.000000
nitrided,861.000000,669.000000,13.000000,206000.000000
nitro-carburized,800.000000,520.000000,13.000000,206000.000000
nitro-case-hard.,1708.000000,1336.500000,12.500000,206000.000000
normalized,623.493421,360.460526,21.118382,206269.736842
pressure die casting,226.333333,146.166667,5.166667,73000.000000
sand casting,249.055556,141.444444,6.666667,73000.000000
tempered at 400 F,1581.206897,1337.655172,10.379310,205793.103448
tempered at 600 F,1454.833333,1229.500000,9.000000,203500.000000
tempered at 800 F,1696.000000,1527.000000,10.500000,207000.000000